import { useEffect, useState } from 'react'
import { useSession } from '../auth/SessionProvider'
import { notificationApi } from './notificationApi'
import type { NotificationPreferences as Preferences } from './notificationApi'

export function NotificationPreferences() {
  const { locale } = useSession(); const es = locale === 'es'; const [value, setValue] = useState<Preferences | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  useEffect(() => { notificationApi.preferences().then(setValue).catch((reason) => setError(reason instanceof Error ? reason.message : String(reason))) }, [])
  async function change(key: keyof Preferences, checked: boolean) { if (!value) return; const next = { ...value, [key]: checked }; setValue(next); try { setValue(await notificationApi.updatePreferences({ [key]: checked })); setNotice(es ? 'Preferencias actualizadas.' : 'Preferences updated.'); setError('') } catch (reason) { setValue(value); setError(reason instanceof Error ? reason.message : String(reason)) } }
  if (!value) return error ? <p className="auth-error">{error}</p> : null
  return <section className="card notification-preferences"><header><p className="eyebrow">{es ? 'AVISOS' : 'NOTIFICATIONS'}</p><h2>{es ? 'Preferencias de notificación' : 'Notification preferences'}</h2><p>{es ? 'Elige qué actividad colaborativa aparece en tu bandeja.' : 'Choose which collaborative activity appears in your inbox.'}</p></header>{notice ? <p className="admin-notice" role="status">{notice}</p> : null}{error ? <p className="auth-error" role="alert">{error}</p> : null}<label><input type="checkbox" checked={value.inAppPlanInvitations} onChange={(event) => void change('inAppPlanInvitations', event.target.checked)} /><span><strong>{es ? 'Invitaciones a planes' : 'Plan invitations'}</strong><small>{es ? 'Avisar cuando alguien comparte un plan contigo.' : 'Notify when someone shares a plan with you.'}</small></span></label><label><input type="checkbox" checked={value.inAppPlanUpdates} onChange={(event) => void change('inAppPlanUpdates', event.target.checked)} /><span><strong>{es ? 'Respuestas a invitaciones' : 'Invitation responses'}</strong><small>{es ? 'Avisar cuando aceptan o rechazan tu invitación.' : 'Notify when your invitation is accepted or declined.'}</small></span></label><label><input type="checkbox" checked={value.emailPlanInvitations} onChange={(event) => void change('emailPlanInvitations', event.target.checked)} /><span><strong>{es ? 'Invitaciones por correo' : 'Email invitations'}</strong><small>{es ? 'Preferencia preparada; los envíos comenzarán cuando SMTP esté habilitado.' : 'Preference is ready; delivery starts when SMTP is enabled.'}</small></span></label></section>
}
