import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useSession } from '../auth/SessionProvider'
import { authApi } from '../auth/authApi'
import type { AccountSession } from '../auth/authTypes'
import { ProfileEditor } from '../account/ProfileEditor'
import { NotificationPreferences } from '../notifications/NotificationPreferences'

export function AccountView() {
  const { session, logout, locale } = useSession(); const user = session!.user; const es = locale === 'es'
  const [sessions, setSessions] = useState<AccountSession[]>([]); const [error, setError] = useState(''); const [workingId, setWorkingId] = useState<string | null>(null); const [verificationSent, setVerificationSent] = useState(false)
  const loadSessions = useCallback(async () => { try { setSessions(await authApi.sessions()); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }, [])
  useEffect(() => { let active = true; authApi.sessions().then((items) => { if (active) setSessions(items) }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : String(cause)) }); return () => { active = false } }, [])
  async function revoke(item: AccountSession) { setWorkingId(item.id); try { const result = await authApi.revokeSession(item.id); if (result.current) { window.location.assign('/login'); return } await loadSessions() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setWorkingId(null) } }
  return <main className="account-page"><div className="account-layout">
    <aside className="card account-navigation"><Link className="account-back-link" to="/plans">← {es ? 'Planes' : 'Plans'}</Link><div className="account-nav-person"><span>{(user.profile?.displayName ?? user.email).slice(0, 1).toUpperCase()}</span><div><strong>{user.profile?.displayName}</strong><small>{user.profile?.code}</small></div></div><nav aria-label={es ? 'Secciones de cuenta' : 'Account sections'}><a href="#overview">⌂ {es ? 'Resumen' : 'Overview'}</a><a href="#contact">◎ {es ? 'Perfil y contacto' : 'Profile and contact'}</a><a href="#preferences">⚙ {es ? 'Preferencias' : 'Preferences'}</a><a href="#security">◇ {es ? 'Seguridad' : 'Security'}</a></nav><button className="btn" onClick={() => void logout()}>{es ? 'Cerrar sesión' : 'Sign out'}</button></aside>
    <div className="account-stack">
      <section className="card account-card" id="overview"><p className="eyebrow">{es ? 'CUENTA' : 'ACCOUNT'}</p><h1>{es ? 'Tu espacio personal' : 'Your personal space'}</h1><p className="account-intro">{es ? 'Administra tu identidad, preferencias y seguridad desde un solo lugar.' : 'Manage your identity, preferences and security in one place.'}</p><div className="account-summary-grid"><div><small>{es ? 'Correo' : 'Email'}</small><strong>{user.email}</strong>{user.emailVerified ? <span className="profile-verified-badge">{es ? 'Verificado' : 'Verified'}</span> : null}</div><div><small>{es ? 'Idioma' : 'Language'}</small><strong>{user.profile?.locale === 'es' ? 'Español' : 'English'}</strong></div><div><small>{es ? 'Zona horaria' : 'Timezone'}</small><strong>{user.profile?.timezone}</strong></div></div>{!user.emailVerified ? <div className="account-verification"><p>{es ? 'Verifica tu correo para proteger tu cuenta.' : 'Verify your email to protect your account.'}</p><button className="btn" type="button" disabled={verificationSent} onClick={() => void authApi.requestEmailVerification(user.email).then(() => setVerificationSent(true)).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause)))}>{verificationSent ? (es ? 'Enlace solicitado' : 'Link requested') : (es ? 'Enviar verificación' : 'Send verification')}</button></div> : null}</section>
      {user.profile ? <ProfileEditor /> : null}
      <div id="preferences"><NotificationPreferences /></div>
      <section className="card account-sessions" id="security" aria-labelledby="sessions-title"><header><p className="eyebrow">{es ? 'SEGURIDAD' : 'SECURITY'}</p><h2 id="sessions-title">{es ? 'Sesiones y dispositivos' : 'Sessions and devices'}</h2><p>{es ? 'Revoca cualquier dispositivo que no reconozcas.' : 'Revoke any device you do not recognize.'}</p></header>{error ? <p className="auth-error" role="alert">{error}</p> : null}<div className="account-session-list">{sessions.map((item) => <article className={item.current ? 'account-session is-current' : 'account-session'} key={item.id}><div className="session-device-icon" aria-hidden="true">{item.device.includes('Android') || item.device.includes('iOS') ? '▯' : '▰'}</div><div><strong>{item.device}</strong><small>{item.current ? (es ? 'Esta sesión' : 'This session') : item.ipAddress ?? (es ? 'IP no disponible' : 'IP unavailable')}</small><small>{es ? 'Última actividad' : 'Last active'}: {new Date(item.lastSeenAt).toLocaleString(es ? 'es-MX' : 'en-US')}</small></div><button className={item.current ? 'btn' : 'btn btn-danger'} type="button" disabled={workingId === item.id} onClick={() => void revoke(item)}>{workingId === item.id ? '…' : item.current ? (es ? 'Cerrar' : 'Sign out') : (es ? 'Revocar' : 'Revoke')}</button></article>)}</div><footer className="account-danger-actions"><Link className="btn" to={`/forgot-password?email=${encodeURIComponent(user.email)}`}>{es ? 'Cambiar contraseña' : 'Change password'}</Link><button className="btn btn-danger" onClick={() => void logout(true)}>{es ? 'Cerrar todas las sesiones' : 'Sign out all sessions'}</button></footer></section>
    </div>
  </div></main>
}
