import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useSession } from '../auth/SessionProvider'
import { authApi } from '../auth/authApi'
import type { AccountSession } from '../auth/authTypes'
import { ProfileEditor } from '../account/ProfileEditor'
import { NotificationPreferences } from '../notifications/NotificationPreferences'

export function AccountView() {
  const { session, logout, locale } = useSession(); const user = session!.user; const es = locale === 'es'
  const [sessions, setSessions] = useState<AccountSession[]>([]); const [error, setError] = useState(''); const [workingId, setWorkingId] = useState<string | null>(null)
  const [verificationSent, setVerificationSent] = useState(false)
  const t = es ? { account: 'CUENTA', back: '← Volver a planes', email: 'Correo', language: 'Idioma', timezone: 'Zona horaria', logout: 'Cerrar sesión', logoutAll: 'Cerrar todas las sesiones' } : { account: 'ACCOUNT', back: '← Back to plans', email: 'Email', language: 'Language', timezone: 'Timezone', logout: 'Sign out', logoutAll: 'Sign out all sessions' }
  const loadSessions = useCallback(async () => { try { setSessions(await authApi.sessions()); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }, [])
  useEffect(() => { let active = true; authApi.sessions().then((items) => { if (active) setSessions(items) }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : String(cause)) }); return () => { active = false } }, [])
  async function revoke(item: AccountSession) { setWorkingId(item.id); try { const result = await authApi.revokeSession(item.id); if (result.current) { window.location.assign('/login'); return } await loadSessions() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setWorkingId(null) } }
  return <main className="account-page"><div className="account-stack"><section className="card account-card"><Link to="/plans">{t.back}</Link><p className="eyebrow">{t.account}</p><h1>{user.profile?.displayName}</h1><p>{user.profile?.code}</p><dl><dt>{t.email}</dt><dd>{user.email} {user.emailVerified ? <span className="profile-verified-badge">{es ? 'Verificado' : 'Verified'}</span> : null}</dd><dt>{t.language}</dt><dd>{user.profile?.locale}</dd><dt>{t.timezone}</dt><dd>{user.profile?.timezone}</dd></dl>{!user.emailVerified ? <div className="account-verification"><p>{es ? 'Verifica tu correo para proteger tu cuenta y habilitar futuros avisos.' : 'Verify your email to protect your account and enable future notifications.'}</p><button className="btn" type="button" disabled={verificationSent} onClick={() => void authApi.requestEmailVerification(user.email).then(() => setVerificationSent(true)).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause)))}>{verificationSent ? (es ? 'Enlace solicitado' : 'Link requested') : (es ? 'Enviar verificación' : 'Send verification')}</button></div> : null}<div className="account-actions">{session?.permissions.includes('user.read') ? <Link className="btn" to="/admin">{es ? 'Administración' : 'Administration'}</Link> : null}<button className="btn" onClick={() => void logout()}>{t.logout}</button><button className="btn btn-danger" onClick={() => void logout(true)}>{t.logoutAll}</button></div></section>
    {user.profile ? <ProfileEditor /> : null}
    <NotificationPreferences />
    <section className="card account-sessions" aria-labelledby="sessions-title"><header><div><p className="eyebrow">{es ? 'SEGURIDAD' : 'SECURITY'}</p><h2 id="sessions-title">{es ? 'Sesiones y dispositivos' : 'Sessions and devices'}</h2><p>{es ? 'Revoca cualquier dispositivo que no reconozcas.' : 'Revoke any device you do not recognize.'}</p></div></header>{error ? <p className="auth-error" role="alert">{error}</p> : null}<div className="account-session-list">{sessions.map((item) => <article className={item.current ? 'account-session is-current' : 'account-session'} key={item.id}><div className="session-device-icon" aria-hidden="true">{item.device.includes('Android') || item.device.includes('iOS') ? '▯' : '▰'}</div><div><strong>{item.device}</strong><small>{item.current ? (es ? 'Esta sesión' : 'This session') : item.ipAddress ?? (es ? 'IP no disponible' : 'IP unavailable')}</small><small>{es ? 'Última actividad' : 'Last active'}: {new Date(item.lastSeenAt).toLocaleString(locale === 'es' ? 'es-MX' : 'en-US')}</small><small>{es ? 'Expira' : 'Expires'}: {new Date(item.expiresAt).toLocaleString(locale === 'es' ? 'es-MX' : 'en-US')}</small></div><button className={item.current ? 'btn' : 'btn btn-danger'} type="button" disabled={workingId === item.id} onClick={() => void revoke(item)}>{workingId === item.id ? '…' : item.current ? (es ? 'Cerrar esta sesión' : 'Sign out this session') : (es ? 'Revocar' : 'Revoke')}</button></article>)}</div></section></div></main>
}
