import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useSession } from '../auth/SessionProvider'
import { collaborationApi } from '../collaboration/collaborationApi'
import type { Conversation, Message, Organization } from '../collaboration/collaborationApi'

export function CollaborationView() {
  const { locale, session } = useSession(); const es = locale === 'es'; const [organizations, setOrganizations] = useState<Organization[]>([]); const [conversations, setConversations] = useState<Conversation[]>([]); const [active, setActive] = useState(''); const [messages, setMessages] = useState<Message[]>([]); const [name, setName] = useState(''); const [code, setCode] = useState(''); const [body, setBody] = useState(''); const [error, setError] = useState('')
  const load = useCallback(() => Promise.all([collaborationApi.organizations(), collaborationApi.conversations()]).then(([orgs, chats]) => { setOrganizations(orgs); setConversations(chats) }).catch((reason) => setError(reason instanceof Error ? reason.message : String(reason))), [])
  useEffect(() => { void load() }, [load]); useEffect(() => { if (active) collaborationApi.messages(active).then(setMessages).catch((reason) => setError(reason instanceof Error ? reason.message : String(reason))) }, [active])
  async function createOrg(event: React.FormEvent) { event.preventDefault(); await collaborationApi.createOrganization(name); setName(''); await load() }
  async function startChat(event: React.FormEvent) { event.preventDefault(); try { const item = await collaborationApi.createConversation(code); setCode(''); setActive(item.id); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)) } }
  async function send(event: React.FormEvent) { event.preventDefault(); if (!active || !body.trim()) return; await collaborationApi.send(active, body.trim()); setBody(''); setMessages(await collaborationApi.messages(active)); await load() }
  const roleLabel = (role: string) => es ? ({ owner: 'propietario', admin: 'administrador', member: 'miembro' }[role] ?? role) : role
  return <main className="collaboration-page"><div className="collaboration-shell"><header className="card collaboration-header"><div><p className="eyebrow">FORGE PLANNER</p><h1>{es ? 'Colaboración' : 'Collaboration'}</h1></div><Link className="btn" to="/plans">{es ? '← Volver a planes' : '← Back to plans'}</Link></header>{error ? <p className="auth-error">{error}</p> : null}<div className="collaboration-grid"><section className="card collaboration-organizations"><h2>{es ? 'Organizaciones' : 'Organizations'}</h2><form onSubmit={createOrg}><input className="field-input" required minLength={2} value={name} onChange={(event) => setName(event.target.value)} placeholder={es ? 'Nombre del equipo' : 'Team name'} /><button className="btn btn-primary" aria-label={es ? 'Crear organización' : 'Create organization'}>+</button></form>{organizations.map((item) => <article key={item.id}><strong>{item.name}</strong><small>{item.members.length} {es ? 'miembros' : 'members'}</small>{item.members.map((member) => <span key={`${item.id}-${member.profile?.code ?? member.role}`}>{member.profile?.displayName ?? roleLabel(member.role)} · {roleLabel(member.role)}</span>)}</article>)}</section><section className="card collaboration-messages"><aside><h2>{es ? 'Mensajes' : 'Messages'}</h2><form onSubmit={startChat}><input className="field-input" required value={code} onChange={(event) => setCode(event.target.value)} placeholder={es ? 'usuario#1234' : 'user#1234'} /><button className="btn" aria-label={es ? 'Iniciar conversación' : 'Start conversation'}>+</button></form>{conversations.map((item) => <button className={active === item.id ? 'conversation-link is-active' : 'conversation-link'} key={item.id} onClick={() => setActive(item.id)}><strong>{item.participants[0]?.displayName ?? (es ? 'Conversación' : 'Conversation')}</strong><small>{item.lastMessage?.body ?? (es ? 'Sin mensajes' : 'No messages')}</small></button>)}</aside><div className="message-thread">{active ? <><div className="message-list">{messages.map((message) => <article className={message.senderUserId === session?.user.id ? 'message-bubble is-mine' : 'message-bubble'} key={message.id}><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString(es ? 'es-MX' : 'en-US')}</small></article>)}</div><form onSubmit={send}><input className="field-input" value={body} onChange={(event) => setBody(event.target.value)} placeholder={es ? 'Escribe un mensaje' : 'Write a message'} /><button className="btn btn-primary">{es ? 'Enviar' : 'Send'}</button></form></> : <p>{es ? 'Selecciona o inicia una conversación.' : 'Select or start a conversation.'}</p>}</div></section></div></div></main>
}
