import { Link } from 'react-router-dom'
import { useRoadmapStore } from '../hooks/useRoadmapStore'

export function LandingView() {
  const locale = useRoadmapStore((state) => state.locale)
  const es = locale === 'es'
  return <main className="landing-page"><header className="landing-nav"><strong>ForgePlanner</strong><nav><Link to="/login">{es ? 'Iniciar sesión' : 'Sign in'}</Link><Link className="btn btn-ghost" to="/register">{es ? 'Crear cuenta' : 'Create account'}</Link></nav></header><section className="landing-hero"><p className="eyebrow">FORGEPLANNER · NORTHSTAR AI</p><h1>{es ? '¿Qué te gustaría lograr?' : 'What would you like to accomplish?'}</h1><p>{es ? 'Convierte tus objetivos en planes claros, editables y accionables con una experiencia de planificación inteligente.' : 'Turn your goals into clear, editable and actionable plans with intelligent planning.'}</p><div className="landing-cta"><Link className="btn btn-primary" to="/ai/plan-proposals">✦ {es ? 'Planear con IA' : 'Plan with AI'}</Link><Link className="btn" to="/plans">{es ? 'Crear manualmente' : 'Create manually'}</Link></div><small>{es ? 'Empieza como invitado y guarda tus planes cuando estés listo.' : 'Start as a guest and save your plans when you are ready.'}</small></section><section className="landing-features"><article><h2>{es ? 'Planificación con IA' : 'AI Planning'}</h2><p>{es ? 'Da forma a tus ideas en propuestas revisables.' : 'Shape ideas into proposals you can review.'}</p></article><article><h2>{es ? 'Roadmaps' : 'Roadmaps'}</h2><p>{es ? 'Organiza objetivos por año y mes.' : 'Organize goals by year and month.'}</p></article><article><h2>{es ? 'Local-first' : 'Local-first'}</h2><p>{es ? 'Comienza sin crear una cuenta.' : 'Start without creating an account.'}</p></article><article><h2>{es ? 'Historial y sincronización' : 'History and sync'}</h2><p>{es ? 'Revisa versiones y guarda en la nube.' : 'Review versions and save securely.'}</p></article></section><section className="landing-how"><h2>{es ? 'Cómo funciona' : 'How it works'}</h2><p>{es ? 'Describe tu objetivo → refínalo con NorthStar AI → aprueba la propuesta → genera y sigue tu plan.' : 'Describe your goal → refine it with NorthStar AI → approve the proposal → create and track your plan.'}</p></section><footer className="landing-footer"><span>ForgePlanner · {es ? 'Impulsado por NorthStar AI' : 'Powered by NorthStar AI'}</span><span><Link to="/privacy">{es ? 'Privacidad' : 'Privacy'}</Link> · <Link to="/terms">{es ? 'Términos' : 'Terms'}</Link> · <a href="mailto:hello@domoforge.com">Contact</a></span><small>Built during OpenAI Build Week 2026 using Codex and GPT-5.6.</small></footer></main>
}

export function LegalView({ kind }: { kind: 'privacy' | 'terms' }) { const es = useRoadmapStore((state) => state.locale) === 'es'; return <main className="legal-page"><Link className="btn btn-ghost" to="/">← ForgePlanner</Link><h1>{kind === 'privacy' ? (es ? 'Política de privacidad' : 'Privacy Policy') : (es ? 'Términos de servicio' : 'Terms of Service')}</h1><p>{kind === 'privacy' ? (es ? 'ForgePlanner procesa la información de cuenta, solicitudes a NorthStar AI y preferencias almacenadas localmente para ofrecer el servicio. Puedes solicitar eliminación de datos contactándonos.' : 'ForgePlanner processes account information, NorthStar AI requests and local preferences to provide the service. You may request deletion by contacting us.') : (es ? 'Usa ForgePlanner de forma responsable. Los planes son editables por ti y las propuestas deben revisarse antes de usarse.' : 'Use ForgePlanner responsibly. Plans remain editable by you and proposals should be reviewed before use.')}</p><p>Contact: hello@domoforge.com</p></main> }
