export const aiProposalCopy = {
  en: {
    title: 'Plan with AI',
    subtitle: 'Describe your goal and review a human-readable proposal before any plan is created.',
    goal: 'What do you want to achieve?',
    options: 'Optional planning details',
    duration: 'Duration',
    hours: 'Time available',
    automatic: 'Automatic',
    generate: 'Generate proposal',
    generating: 'Preparing proposal…',
    warning: 'Do not enter passwords, authentication tokens, bank account information, Social Security numbers, medical records, or other highly sensitive information.',
    dismissWarning: 'Dismiss sensitive-data warning',
    objective: 'Primary objective',
    phases: 'Phases',
    assumptions: 'Assumptions',
    risks: 'Risks',
    warnings: 'Warnings',
    indicators: 'Success indicators',
    instruction: 'What should change?',
    applyRefinement: 'Apply refinement',
    use: 'Use this proposal',
    reject: 'Reject proposal',
    notCreated: 'The final plan structure has not been created yet.',
    empty: 'No proposals yet.',
    back: 'Back to plans',
    refinementCount: 'Refinements',
    greeting: 'Tell me what you want to accomplish. We will review a proposal together before creating any plan.',
    scope: 'Scope',
    focused: 'Focused',
    balanced: 'Balanced',
    comprehensive: 'Comprehensive',
    complexity: 'Complexity',
    simple: 'Simple',
    moderate: 'Moderate',
    advanced: 'Advanced',
    detail: 'Detail level',
    overview: 'Overview',
    detailed: 'Detailed',
    steps: 'Step by step',
    financial: 'Financial context',
    none: 'None',
    budget: 'Monthly budget',
    savings: 'Savings goal',
    currency: 'Currency',
    custom: 'Custom',
    clear: 'Clear',
    monthsShort: 'mo',
    hoursShort: 'h',
    startOver: 'Start over',
    startOverTitle: 'Start over',
    startOverBody: 'Your goal, planning context, and all changes made to this proposal will be lost.',
    startOverQuestion: 'Do you want to continue?',
    cancel: 'Cancel',
    you: 'You',
    assistant: 'NorthStar AI',
    send: 'Send goal',
    sendAnswer: 'Send answer',
    answer: 'Your answer',
    continueAssumptions: 'Continue with assumptions',
    acceptProposal: 'Accept proposal',
    refineProposal: 'Refine',
    continueTalking: 'Continue talking',
    proposalDuration: 'Recommended duration',
    editRequest: 'Describe the change or add more context',
    resume: 'Previous conversations',
    sessionStartError: "We couldn't start the planning session. Try again.",
    retrySession: 'Try again',
    typing: 'NorthStar AI is writing a response.',
    revealMessage: 'Reveal full response',
    selected: 'Selected',
    requestError: "We couldn't complete the request. Try again.",
    sensitiveInputError: 'Remove highly sensitive credentials or identity information before continuing.',
    statusPending: 'Pending',
    statusProposed: 'Proposal ready',
    statusRefining: 'Refining',
    statusReady: 'Ready',
    statusRejected: 'Rejected',
    statusFailed: 'Failed',
    statusExpired: 'Expired',
    statusConverting: 'Building plan',
    statusPreview: 'Plan preview ready',
    statusConversionFailed: 'Conversion failed',
    statusCompleted: 'Plan created',
    planPreview: 'Plan preview',
    planDuration: 'Plan window',
    goalsCount: 'Goals',
    milestonesCount: 'Milestones',
    activitiesCount: 'Activities',
    planningMode: 'Planning mode',
    savingsEnabled: 'Savings tracking',
    enabled: 'Enabled',
    disabled: 'Disabled',
    createThisPlan: 'Create this plan',
    regenerateStructure: 'Regenerate structure',
    backToProposal: 'Back to proposal',
    openPreview: 'Open plan preview',
    conversionError: "We couldn't build a valid plan structure. Try again.",
    creatingPlan: 'Creating plan…',
  },
  es: {
    title: 'Planear con IA',
    subtitle: 'Describe tu objetivo y revisa una propuesta legible antes de crear cualquier plan.',
    goal: '¿Qué quieres lograr?',
    options: 'Detalles opcionales de planificación',
    duration: 'Duración',
    hours: 'Tiempo disponible',
    automatic: 'Automático',
    generate: 'Generar propuesta',
    generating: 'Preparando propuesta…',
    warning: 'No ingreses contraseñas, tokens de autenticación, información de cuentas bancarias, números de Seguro Social, expedientes médicos ni otra información altamente sensible.',
    dismissWarning: 'Cerrar advertencia sobre datos sensibles',
    objective: 'Objetivo principal',
    phases: 'Fases',
    assumptions: 'Supuestos',
    risks: 'Riesgos',
    warnings: 'Advertencias',
    indicators: 'Indicadores de éxito',
    instruction: '¿Qué debería cambiar?',
    applyRefinement: 'Aplicar refinamiento',
    use: 'Usar esta propuesta',
    reject: 'Rechazar propuesta',
    notCreated: 'La estructura final del plan todavía no se ha creado.',
    empty: 'Todavía no hay propuestas.',
    back: 'Volver a planes',
    refinementCount: 'Refinamientos',
    greeting: 'Cuéntame qué quieres lograr. Revisaremos juntos una propuesta antes de crear cualquier plan.',
    scope: 'Alcance',
    focused: 'Enfocado',
    balanced: 'Equilibrado',
    comprehensive: 'Integral',
    complexity: 'Complejidad',
    simple: 'Simple',
    moderate: 'Moderada',
    advanced: 'Avanzada',
    detail: 'Nivel de detalle',
    overview: 'Amplio',
    detailed: 'Detallado',
    steps: 'Paso a paso',
    financial: 'Contexto financiero',
    none: 'Ninguno',
    budget: 'Presupuesto mensual',
    savings: 'Meta de ahorro',
    currency: 'Moneda',
    custom: 'Personalizado',
    clear: 'Limpiar',
    monthsShort: 'meses',
    hoursShort: 'h',
    startOver: 'Comenzar de nuevo',
    startOverTitle: 'Comenzar de nuevo',
    startOverBody: 'Se perderán el objetivo, el contexto y todos los cambios realizados en esta propuesta.',
    startOverQuestion: '¿Deseas continuar?',
    cancel: 'Cancelar',
    you: 'Tú',
    assistant: 'NorthStar AI',
    send: 'Enviar objetivo',
    sendAnswer: 'Enviar respuesta',
    answer: 'Tu respuesta',
    continueAssumptions: 'Continuar con supuestos',
    acceptProposal: 'Aceptar propuesta',
    refineProposal: 'Refinar',
    continueTalking: 'Seguir conversando',
    proposalDuration: 'Duración recomendada',
    editRequest: 'Describe el cambio o agrega más contexto',
    resume: 'Conversaciones anteriores',
    sessionStartError: 'No pudimos iniciar la sesión de planificación. Inténtalo de nuevo.',
    retrySession: 'Intentar de nuevo',
    typing: 'NorthStar AI está escribiendo una respuesta.',
    revealMessage: 'Mostrar la respuesta completa',
    selected: 'Seleccionado',
    requestError: 'No pudimos completar la solicitud. Inténtalo de nuevo.',
    sensitiveInputError: 'Elimina credenciales o información de identidad altamente sensible antes de continuar.',
    statusPending: 'Pendiente',
    statusProposed: 'Propuesta lista',
    statusRefining: 'Refinando',
    statusReady: 'Lista',
    statusRejected: 'Rechazada',
    statusFailed: 'Fallida',
    statusExpired: 'Vencida',
    statusConverting: 'Creando estructura',
    statusPreview: 'Vista previa lista',
    statusConversionFailed: 'Falló la conversión',
    statusCompleted: 'Plan creado',
    planPreview: 'Vista previa del plan',
    planDuration: 'Ventana del plan',
    goalsCount: 'Objetivos',
    milestonesCount: 'Hitos',
    activitiesCount: 'Actividades',
    planningMode: 'Modo de planificación',
    savingsEnabled: 'Seguimiento de ahorro',
    enabled: 'Activado',
    disabled: 'Desactivado',
    createThisPlan: 'Crear este plan',
    regenerateStructure: 'Regenerar estructura',
    backToProposal: 'Volver a la propuesta',
    openPreview: 'Abrir vista previa',
    conversionError: 'No pudimos crear una estructura de plan válida. Inténtalo de nuevo.',
    creatingPlan: 'Creando plan…',
  },
} as const

export type AiProposalCopy = (typeof aiProposalCopy)[keyof typeof aiProposalCopy]
