import { useEffect, useState } from 'react'
import { adminApi } from './adminApi'
import type { EmailTemplate } from './adminApi'

export function EmailTemplateEditor({ locale }: { locale: 'es' | 'en' }) {
  const es = locale === 'es'; const [template, setTemplate] = useState<EmailTemplate | null>(null); const [preview, setPreview] = useState<{ subject: string; html: string; text: string } | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  useEffect(() => { adminApi.emailTemplate().then(setTemplate).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))) }, [])
  if (!template) return error ? <p className="auth-error">{error}</p> : <p>{es ? 'Cargando plantilla…' : 'Loading template…'}</p>
  const content = { subject: template.subject, htmlBody: template.htmlBody, textBody: template.textBody }
  async function save() { try { setTemplate(await adminApi.updateEmailTemplate(content)); setNotice(es ? 'Plantilla guardada.' : 'Template saved.'); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }
  async function showPreview() { try { setPreview(await adminApi.previewEmailTemplate(content)); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }
  async function reset() { try { setTemplate(await adminApi.resetEmailTemplate()); setPreview(null); setNotice(es ? 'Se restauró la plantilla predeterminada.' : 'Default template restored.'); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }
  return <section className="admin-content card template-editor"><header><div><h2>{es ? 'Recuperación de contraseña' : 'Password recovery'}</h2><p>{es ? `Versión ${template.version} · origen: ${template.source === 'database' ? 'personalizada' : 'predeterminada'}` : `Version ${template.version} · source: ${template.source}`}</p></div><div className="template-tags">{template.allowedTags.map((tag) => <code key={tag}>{`{{${tag}}}`}</code>)}</div></header>{error ? <p className="auth-error" role="alert">{error}</p> : null}{notice ? <p className="admin-notice" role="status">{notice}</p> : null}<label className="field-wrap"><span>{es ? 'Asunto' : 'Subject'}</span><input className="field-input" value={template.subject} onChange={(event) => setTemplate({ ...template, subject: event.target.value })} /></label><div className="template-editor-grid"><label className="field-wrap"><span>HTML</span><textarea className="field-input template-code-field" value={template.htmlBody} onChange={(event) => setTemplate({ ...template, htmlBody: event.target.value })} /></label><label className="field-wrap"><span>{es ? 'Texto plano' : 'Plain text'}</span><textarea className="field-input template-code-field" value={template.textBody} onChange={(event) => setTemplate({ ...template, textBody: event.target.value })} /></label></div><footer className="template-actions"><button className="btn btn-danger" type="button" onClick={() => void reset()}>{es ? 'Restaurar predeterminada' : 'Restore default'}</button><button className="btn" type="button" onClick={() => void showPreview()}>{es ? 'Vista previa' : 'Preview'}</button><button className="btn btn-primary" type="button" onClick={() => void save()}>{es ? 'Guardar plantilla' : 'Save template'}</button></footer>{preview ? <section className="template-preview"><header><strong>{preview.subject}</strong><button className="btn btn-ghost" onClick={() => setPreview(null)}>×</button></header><iframe title={es ? 'Vista previa del correo' : 'Email preview'} sandbox="" srcDoc={preview.html} /><details><summary>{es ? 'Versión en texto' : 'Text version'}</summary><pre>{preview.text}</pre></details></section> : null}</section>
}
