import { Router } from 'express'
import type { PrismaClient } from '@prisma/client'
import { ApiError } from '../../http/errors.js'
import { csrfProtection, requireAuth } from '../auth/auth.middleware.js'
import { messageSchema, organizationMemberSchema, organizationSchema, profileCodeInputSchema, uuidSchema } from './collaboration.schemas.js'

const profileSelect = { displayName: true, handle: true, discriminator: true, avatarUrl: true } as const
const profileDto = (profile: { displayName: string; handle: string; discriminator: string; avatarUrl: string | null }) => ({ ...profile, code: `${profile.handle}#${profile.discriminator}` })
function slug(name: string) { return `${name.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 55) || 'team'}-${crypto.randomUUID().slice(0, 8)}` }

export function collaborationRoutes(db: PrismaClient) {
  const router = Router(); router.use(requireAuth)
  router.get('/organizations', async (request, response) => { const items = await db.organization.findMany({ where: { members: { some: { userId: request.auth!.effectiveUserId } } }, include: { members: { include: { user: { select: { profile: { select: profileSelect } } } } } }, orderBy: { updatedAt: 'desc' } }); response.json({ organizations: items.map((item) => ({ ...item, members: item.members.map((member) => ({ role: member.role, joinedAt: member.joinedAt, profile: member.user.profile ? profileDto(member.user.profile) : null })) })) }) })
  router.post('/organizations', csrfProtection, async (request, response) => { const input = organizationSchema.parse(request.body); const organization = await db.organization.create({ data: { name: input.name, slug: slug(input.name), members: { create: { userId: request.auth!.effectiveUserId, role: 'owner' } } } }); response.status(201).json({ organization }) })
  router.post('/organizations/:organizationId/members', csrfProtection, async (request, response) => { const organizationId = uuidSchema.parse(request.params.organizationId); const input = organizationMemberSchema.parse(request.body); const authorized = await db.organizationMember.findFirst({ where: { organizationId, userId: request.auth!.effectiveUserId, role: { in: ['owner', 'admin'] } } }); if (!authorized) throw new ApiError(404, 'ORGANIZATION_NOT_FOUND', 'Organization not found.'); const [handle, discriminator] = input.profileCode.toLowerCase().split('#'); const target = await db.profile.findFirst({ where: { handle, discriminator, searchable: true, user: { status: 'active' } } }); if (!target) throw new ApiError(404, 'PROFILE_NOT_FOUND', 'Public profile not found.'); await db.organizationMember.upsert({ where: { organizationId_userId: { organizationId, userId: target.userId } }, create: { organizationId, userId: target.userId, role: input.role }, update: { role: input.role } }); response.status(201).json({ added: true }) })
  router.get('/conversations', async (request, response) => { const items = await db.conversation.findMany({ where: { participants: { some: { userId: request.auth!.effectiveUserId } } }, include: { participants: { include: { user: { select: { profile: { select: profileSelect } } } } }, messages: { where: { deletedAt: null }, orderBy: { createdAt: 'desc' }, take: 1 } }, orderBy: { updatedAt: 'desc' } }); response.json({ conversations: items.map((item) => ({ id: item.id, updatedAt: item.updatedAt, participants: item.participants.filter((participant) => participant.userId !== request.auth!.effectiveUserId).map((participant) => participant.user.profile ? profileDto(participant.user.profile) : null).filter(Boolean), lastMessage: item.messages[0] ?? null })) }) })
  router.post('/conversations', csrfProtection, async (request, response) => { const input = profileCodeInputSchema.parse(request.body); const [handle, discriminator] = input.profileCode.toLowerCase().split('#'); const target = await db.profile.findFirst({ where: { handle, discriminator, searchable: true, user: { status: 'active' }, userId: { not: request.auth!.effectiveUserId } } }); if (!target) throw new ApiError(404, 'PROFILE_NOT_FOUND', 'Public profile not found.'); const candidates = await db.conversation.findMany({ where: { participants: { some: { userId: request.auth!.effectiveUserId } } }, include: { participants: true } }); const existing = candidates.find((item) => item.participants.length === 2 && item.participants.some((participant) => participant.userId === target.userId)); const conversation = existing ?? await db.conversation.create({ data: { participants: { create: [{ userId: request.auth!.effectiveUserId }, { userId: target.userId }] } } }); response.status(existing ? 200 : 201).json({ conversation: { id: conversation.id } }) })
  router.get('/conversations/:conversationId/messages', async (request, response) => { const conversationId = uuidSchema.parse(request.params.conversationId); const membership = await db.conversationParticipant.count({ where: { conversationId, userId: request.auth!.effectiveUserId } }); if (!membership) throw new ApiError(404, 'CONVERSATION_NOT_FOUND', 'Conversation not found.'); const messages = await db.message.findMany({ where: { conversationId, deletedAt: null }, orderBy: { createdAt: 'asc' }, take: 200 }); response.json({ messages }) })
  router.post('/conversations/:conversationId/messages', csrfProtection, async (request, response) => { const conversationId = uuidSchema.parse(request.params.conversationId); const input = messageSchema.parse(request.body); const membership = await db.conversationParticipant.count({ where: { conversationId, userId: request.auth!.effectiveUserId } }); if (!membership) throw new ApiError(404, 'CONVERSATION_NOT_FOUND', 'Conversation not found.'); const message = await db.$transaction(async (tx) => { const created = await tx.message.create({ data: { conversationId, senderUserId: request.auth!.effectiveUserId, body: input.body } }); await tx.conversation.update({ where: { id: conversationId }, data: { updatedAt: new Date() } }); return created }); response.status(201).json({ message }) })
  return router
}
